# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://pabloclemxnte.github.io/proba_lib/"

git_url = "https://github.com/pabloclemxnte/proba_lib/tree/master/"

def custom_doc_links(name): return None
